/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/assets/glb/logo.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.OuterCircle.geometry}
        material={materials.parteExterna}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.glass.geometry}
        material={materials.vidrio}
        position={[5.1459503, -0.6646184, -5.1208005]}
        scale={5.0002642}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.I001.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.dot1.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.M.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.dot2.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.A001.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.G001.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.do4.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={[119.137558, 91.5366745, 119.137558]}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.dot3.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.E001.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.R.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.T.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.Y.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.O.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.A.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.C.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.F.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.S.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.I.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.E.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.D.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.G.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.N.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.rw1.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.rw2.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.rw3.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.rw4.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.rw5.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.lw1.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.lw2.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.lw3.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.lw4.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.lw5.geometry}
        material={materials.plastico}
        position={[-0.0592716, 0.0076551, 0.0589817]}
        scale={119.137558}
      />
    </group>
  );
}

useGLTF.preload('/logo.glb');
